export const MOVE_FROM_NEW_TO_PROCESSING = "MOVE_FROM_NEW_TO_PROCESSING";
export const SAVE_NEW_ORDERS = "SAVE_NEW_ORDERS";
export const SAVE_NEW_ORDER = "SAVE_NEW_ORDER";
export const SAVE_ORDERS_IN_PREPARATION = "SAVE_ORDERS_IN_PREPARATION";
export const SAVE_ORDERS_IN_SERVED = "SAVE_ORDERS_IN_SERVED";
export const SAVE_ORDERS_IN_COMPLETED = "SAVE_ORDERS_IN_COMPLETED";
export const CHANGE_STATUS = "CHANGE_STATUS";
